/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mclaren.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mclaren.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh10.geometry} material={nodes.Mesh10.material} />
    </group>
  )
}

useGLTF.preload('/mclaren.glb')
